openapi: '3.0.0'
info:
  title: 'File Comparison API'
  version: '1.0.0'
  description: 'API to upload two files and compare them'
paths:
  /upload:
    post:
      x-openapi-router-controller: api_server.controllers.file_controller
      operationId: upload_files
      summary: 'Upload and compare files'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file1:
                  type: string
                  format: binary
                  description: 'The first Word file'
                file2:
                  type: string
                  format: binary
                  description: 'The second Word file'
                type:
                  type: string
                  description: 'Type parameter to select parser (A or B)'
      responses:
        '200':
          description: 'Comparison result'
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: 'Comparison result'